### PR TITLE
update html, js and css 

### PR DESCRIPTION
**Pull request by Trinidad-KianLee**
I have updated my html, js and css for the new features of my web. Please take a look and review my code. Thank you!

### CODE REVIEW

**Review by Dimasacat-Andronicus — CHANGES_REQUESTED** [review]
*In your folder* Kindly check the boxes if your done with it.

On your index html file 
- [x] Your reference link is broken, you can do it by making the link like this: "./Myworks.html"

https://github.com/PUP-BSIT/exercise-13-sixth_sense/blob/d1b1f200b274897e71d6983bd74847ac9f6aed9f/trinidad_kianlee/index.html#L27-L30
https://github.com/PUP-BSIT/exercise-13-sixth_sense/blob/c61f376fc837723005e4b06c81f2d9314e3a0b86/trinidad_kianlee/index.html#L6
https://github.com/PUP-BSIT/exercise-13-sixth_sense/blob/d1b1f200b274897e71d6983bd74847ac9f6aed9f/trinidad_kianlee/index.html#L186

- Optional, you can remove unnecessary space in your html file so it can slightly reduce the file size which can improve loading of your page.

Something like this: https://github.com/PUP-BSIT/exercise-13-sixth_sense/blob/d1b1f200b274897e71d6983bd74847ac9f6aed9f/trinidad_kianlee/index.html#L13 
https://github.com/PUP-BSIT/exercise-13-sixth_sense/blob/d1b1f200b274897e71d6983bd74847ac9f6aed9f/trinidad_kianlee/index.html#L23

On your Script File
- [x] Much better to use querySelector instead of getElement method.

Something like this, kindly edit your script file: 
https://github.com/PUP-BSIT/exercise-13-sixth_sense/blob/d1b1f200b274897e71d6983bd74847ac9f6aed9f/trinidad_kianlee/script.js#L4-L6

On your UI
- [x] In your website, make styling for your comment section to be much readable.

**Comment by Trinidad-KianLee** [comment]
@Dimasacat-Andronicus I've fixed my code thanks to your guidance. I kindly ask for code review again for my changes. Thank you!!

**Review by Dimasacat-Andronicus — CHANGES_REQUESTED** [review]
- [ ] Place the script header before closing tag of body. 
https://github.com/PUP-BSIT/exercise-13-sixth_sense/blob/2d29b892eb41c79e61f8200ee1bb6eb4ed73f5f0/trinidad_kianlee/index.html#L7

**Comment by Trinidad-KianLee** [comment]
@Dimasacat-Andronicus I've fixed the last errors that I made. Thank you for guiding me improvise my code.

**Review by Dimasacat-Andronicus — CHANGES_REQUESTED** [review]
- [x] Lastly, make sure that your files is less than 80 columns to be sure.

Something like this:
https://github.com/PUP-BSIT/exercise-13-sixth_sense/blob/1884c2cd108b742f6c8250add8da74805c041d1a/trinidad_kianlee/index.html#L67

**Comment by Trinidad-KianLee** [comment]
@Dimasacat-Andronicus I've adjust the column lines. Thank you!

**Review by Dimasacat-Andronicus — CHANGES_REQUESTED** [review]
@Trinidad-KianLee 
- [x] Remove spaces here. 
https://github.com/PUP-BSIT/exercise-13-sixth_sense/blob/8917f1ca93a0067d63cbef28b5f24a417561fc03/trinidad_kianlee/trinidad_style.css#L375-L376

**Comment by Trinidad-KianLee** [comment]
@Dimasacat-Andronicus I've removed the extra spaces in my css file. Thank you!

**Review by Dimasacat-Andronicus — APPROVED** [review]
@Trinidad-KianLee 
I think that should be good. Kindly review your own code just to be sure it's good to go before merging to the main branch.

**Comment by Trinidad-KianLee** [comment]
@Dimasacat-Andronicus Thank you for guiding me to improve my code!

**Pull request merged**
