### PR TITLE
update html, css, js and readme file

### PR DESCRIPTION
**Pull request by Gasta-Marc-Oliver**
Hello, I already updated my all the files as well as the readme please kindly check it. Thank you!

### CODE REVIEW

**Comment by go-christianharrel** [comment]
https://github.com/PUP-BSIT/exercise-13-sixth_sense/blob/b7e45fab95a2bf462395992792fd7c43f392f473/gasta_marcoliver/index.html#L159

Your javascript file name seems wrong. change it to `script.js`

**Comment by go-christianharrel** [comment]
https://github.com/PUP-BSIT/exercise-13-sixth_sense/blob/b7e45fab95a2bf462395992792fd7c43f392f473/gasta_marcoliver/index.html#L93-L102

I suggest you make it like this:
```html
      <p>
        I think the reason for the f-t-f class is because of cruciality 
        of the lesson. It might be hard for us to learn it if we did an class.
        For me, online class can be abused in a lot of ways. As the teacher 
        can't see as or observe us during the session. On the other hand, 
        it is helpfull especially to those persons who lives far from 
        the campus. Personally, I prefer face to face classes in this subject 
        because I think I learn more if its face to face rather than online 
        classes. As in online classes I can be very easily distracted 
        from other things.
      </p>

**Comment by go-christianharrel** [comment]
**Suggested code on your javascript.** 

```javascript
// Applied guard clauses for input validation and to prevent unnecessary code execution.
// Utilized querySelector instead of getElementById for more flexible element selection.
// Utilized querySelector instead of getElementById
``` 

Click [here](https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit?pli=1#slide=id.g25d183194fb_0_0) to view the guidelines.

```JAVASCRIPT
function validate_input() {
    const input_field = document.querySelector("#name_input");
    const comment_field = document.querySelector("#comment_input");
    const submit_btn = document.querySelector("#submit_btn");
  
    // Guard clause to disable submit button if input fields are empty
    if (
      input_field.value.trim().length === 0 ||
      comment_field.value.trim().length === 0
    ) {
      submit_btn.disabled = true;
      submit_btn.classList.add("disabled");
      return;
    }
  
    submit_btn.disabled = false;
    submit_btn.classList.remove("disabled");
  }
  
  let comments = [];
  
  function render_comments(sort_order = "asc") {
    const comment_list = document.querySelector("#comment-list");
    comment_list.innerHTML = "";
  
    const sorted_comments = comments.slice().sort((a, b) => {
      const date_a = new Date(a.date);
      const date_b = new Date(b.date);
      return sort_order === "asc" ? date_a - date_b : date_b - date_a;
    });
  
    sorted_comments.forEach((comment) => {
      const comment_element = document.createElement("div");
      comment_element.classList.add("comment");
      comment_element.innerHTML = `
        <h4>${comment.name}</h4>
        <p>${comment.text}</p>
        <small>${comment.date.toLocaleString()}</small>`;
      comment_list.appendChild(comment_element);
    });
  }
  
  document.querySelector("#comment_form").addEventListener("submit", (e) => {
    e.preventDefault();
    const name_input = document.querySelector("#name_input");
    const comment_input = document.querySelector("#comment_input");
  
    // Guard clause to prevent submission if input fields are empty
    if (!name_input.value.trim() || !comment_input.value.trim()) {
      return;
    }
  
    const new_comment = {
      name: name_input.value,
      text: comment_input.value,
      date: new Date(),
    };
  
    comments.push(new_comment);
  
    name_input.value = "";
    comment_input.value = "";
  
    render_comments(document.querySelector("#sort_order").value);
  });
  
  document.querySelector("#sort_order").addEventListener("change", () => {
    render_comments(document.querySelector("#sort_order").value);
  });
  
  render_comments();

**Review by go-christianharrel — APPROVED** [review]
LGTM

**Comment by Gasta-Marc-Oliver** [comment]
Thank you @go-christianharrel!

**Pull request merged**
